const siteContent = {
  "writing": [
    {
      "kind": "writing",
      "title": "AI-generated Bermanisms",
      "slug": "ai_generated_bermanisms",
      "importance": 60,
      "metaDescription": "Jared \"Take A Load\" Goff or Jared \"Turn Your Head and\" Goff?",
      "homeCardText": "Jared \"Take A Load\" Goff --or--[br]Jared \"Turn Your Head and\" Goff?",
      "archiveCardText": "Jared \"Take A Load\" Goff --or--[br]Jared \"Turn Your Head and\" Goff?",
      "archiveCardClass": "",
      "pageIntroText": "",
      "detailPageEnabled": true,
      "homeHref": "./ai_generated_bermanisms.html",
      "archiveHref": "./ai_generated_bermanisms.html",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "",
          "text": "I started experimenting with LLMs in 2021, when I signed up for an OpenAI API key and began testing early GPT models like [code]davinci[/code] and [code]babbage[/code]. Since then, I have been using one benchmark on every new model that I can access: [b]Can the AI produce good Bermanisms?[/b]\n\nIf you are not familiar, [link https://en.wikipedia.org/wiki/Chris_Berman]Chris \"Boomer\" Berman[/link] is a sportscaster who has been on ESPN since 1979. He is known for many things, but one of his most iconic contributions to American culture is the pun-based nicknames that he gives to professional athletes. The nickname never has anything to do with the sport or any characteristics of the athlete. It's all about the chuckle.\n\nHere are some of my all-time favorite Berman-generated Bermanisms:\n\nJeff \"Brown Paper\" Bagwell (MLB)[br]Steve \"Dorsal\" Finley (MLB)[br]Bert \"Be Home\" Blyleven (MLB)[br]Ben \"Winter\" Coates (NFL)[br]Carlos \"1 if by Sea, 2 if by Land, 3 if\" Baerga (MLB)[br]Scott \"Supercalifragalisticexpliala\" Brosius (MLB)[br]Andre \"Bad Moon\" Rison (NFL)[br]Vince Workman \"My Way Back to You Babe\" (NFL)[br]Sammy \"Say it Ain't\" Sosa (MLB)[br]Roberto \"Remember the \" Alomar (MLB)[br]Bernard \"Innocent until proven\" Gilkey (MLB)\n\nI've been very impressed with many AI-generated language tasks that LLMs have produced in recent years, especially creative tasks like writing lyrics for songs and poetry. But it's been really bad at Bermanisms.\n\nHere is the prompt I've been using:\n\n[i]Do you know what Bermanisms are? Here are some examples:[br]Jeff \"Brown Paper\" Bagwell[br]Mike Carreon \"My Wayward Sun\"[br]Steve \"Dorsal\" Finley[br]Bernard \"Innocent until proven\" Gilkey[br]Darryl \"Green Eggs &\" Hamilton[br]Jeff Conine \"The Barbarian\"[br]Carlos \"1 if by Sea, 2 if by Land, 3 if\" Baerga[br]Roberto \"Remember the \" Alomar[br]Jeff \"See Through\" Blauser[br]Scott \"Supercalifragalisticexpliala\" Brosius[br]Sammy \"Say it Ain't\" Sosa[br]Eddie \"Eat Drink & Be\" Murray[br]Bert \"Be Home\" Blyleven[br]Ben \"Winter\" Coates[br]Mike \"You're in Good Hands with\" Alstott[br]Jake \"Daylight come and I wanna\" Delhomme[br]Andre \"Bad Moon\" Rison[br]Vince Workman \"My Way Back to You Babe\"[br]Jeff \"Philadelphia\" Feagles[br][br]I want to see if you can creat some original Bermanisms. Come up with 40 original Bermanisms for current NFL players. Every time you generate one, go back and compare it to the examples I have given and verify that it is a legitimate Bermanism. No need to explain the logic, just list 40 Bermanisms without numbering or bullets.[/i]\n\nChatGPT 5.2 (Thinking) is horrible at this task. Here are some examples of its output:\n\nPatrick “Mahomes Is Where the Heart Is” Mahomes[br]Josh “Allen Town” Allen[br]Lamar “La-Mar-a-Lago” Jackson[br]Joe “Burrow My Sunshine” Burrow[br]Jalen “Hurts So Good” Hurts[br]Christian “McCaffreeyoncé” McCaffrey[br]Tyreek “Hill Street Blues” Hill[br]Travis “Kelce Lately” Kelce\n\nAs you can see, these are bad. Some of them are clever, but they don't follow the logic of the many-shots (examples) that I provided. This is typical of LLM output over the years. But I always knew that it was possible for models to do better; that it was a matter of time before models could produce genuine Bermanisms.\n\nEnter Anthropic's Opus 4.6 (released February 5, 2026). Here is it's response to my prompt:\n\nJalen \"Love\" Hurts[br]CeeDee \"Silence of the\" Lamb[br]TJ \"Kilo\" Watt[br]Patrick \"My Old Kentucky\" Mahomes[br]Ja'Marr \"Cut to the\" Chase[br]Tyreek \"Over the\" Hill[br]Cooper \"Stanley\" Kupp[br]George \"A Fine\" Kittle[br]Davante \"Gomez &\" Adams[br]Kirk \"Kissin'\" Cousins[br]Jared \"Blast\" Goff[br]Breece \"Deck the\" Hall[br]Trey \"Here Comes the\" McBride[br]Maxx \"Bing\" Crosby[br]Derrick \"O.\" Henry[br]Lamar \"Action\" Jackson[br]Kyle \"Alexander\" Hamilton[br]Jayden \"Jack\" Daniels[br]Malik \"Good\" Nabers[br]Mark \"St.\" Andrews[br]Brock \"Sit Up and Look\" Purdy[br]Jordan \"What is\" Love[br]Deebo \"Uncle\" Samuel[br]Saquon \"Charles\" Barkley[br]Kenneth \"Johnnie\" Walker[br]Justin \"George\" Jefferson[br]Drake \"Jack\" London[br]Joe \"Down the Rabbit\" Burrow[br]Fred \"Bros.\" Warner[br]Nico \"Tom\" Collins[br]Zack \"A Rolling Stone Gathers No\" Moss[br]Pat \"That's for\" Surtain[br]Sauce \"Madison Square\" Gardner[br]Chuba \"Old Mother\" Hubbard[br]Rachaad \"Snow\" White[br]Tyler \"Davy Jones'\" Lockett[br]Jerry \"Judge\" Jeudy[br]D'Andre \"Taylor\" Swift[br]Amari \"Mini\" Cooper[br]James \"Captain\" Cook\n\nThese are much better. A lot of them are not good, but many of them genuinely made me laugh, as any good Bermanism should. I really loved [b]Sauce \"Madison Square\" Gardner![/b] Here are some more Opus gems that I've come across in other sessions:\n\nZay \"April Showers Bring May\" Flowers[br]Cooper \"Fill My\" Kupp[br]Jordan \"Whole Lotta\" Love[br]Aidan \"Starsky &\" Hutchinson[br]Tank \"Farmer in the\" Dell[br]Brock \"She Sure Looks\" Purdy\n\nNext up is the latest major model to be released, Google Gemini 3.1 Pro (February 19, 2026). Gemini 3.1 Pro does somethings better than any other model, but one thing it can't do is freaking count (or at least follow instructions). It repeatedly fails to produce 40 Bermanisms (Opus had no trouble doing this). Anyway here are the \"40\" Bermanisms it produced in the latest run:\n\nPatrick \"Take Me\" Mahomes[br]Joe \"Beg, Steal, or\" Burrow[br]C.J. \"Two's Company, Three's a\" Stroud[br]Lamar \"I'm Sorry Ms.\" Jackson[br]Josh \"Up and\" Allen[br]Justin \"Movin' On Up\" Jefferson[br]CeeDee \"Mary Had a Little\" Lamb[br]Tyreek \"Over the\" Hill[br]Breece \"Deck the\" Hall[br]De'Von \"Ball and\" Achane[br]D'Andre \"Tailor\" Swift[br]Cooper \"Half Full\" Kupp[br]Jared \"Shake It\" Goff[br]T.J. \"Turn Down For\" Watt[br]Myles \"To Go Before I Sleep\" Garrett[br]Fred \"Pop\" Warner[br]Aidan \"Starsky and\" Hutchinson\n\nI haven't been seeing a lot of overlap in the outputs, but Opus and Gemini 3.1 Pro consistently produce [i]Aidan \"Starsky and\" Hutchinson[/i]. Of these Gemini Bermanisms, my favorite is [b]C.J. \"Two's Company, Three's a\" Stroud[/b]. I also really like [b]Myles \"To Go Before I Sleep\" Garrett[/b]. Here are some other Bermanisms from previous sessions with Gemini 3.1 Pro that made me laugh:\n\nBrock \"I Feel\" Purdy[br]Chris \"Extra Virgin\" Olave[br]Cooper \"Peanut Butter\" Kupp[br]Jalen \"Everybody\" Hurts[br]George \"Slim\" Pickens[br]Saquon \"All Bite No\" Barkley[br]Patrick \"Lights Are On But Nobody's\" Mahomes[br]Jared \"Take a Load\" Goff[br]Jared \"Turn Your Head and\" Goff[br]Kyle \"Bottomless\" Pitts\n\nI don't hold it against the models that they still have so many misfires. I'm sure Berman (and his writers) toss plenty of potential Bermanisms in the waste paper basket and we only see the cream of the crop on TV.\n\nI'll follow up this post with new experiments when the next generation of models is released (at this rate, probably next week!).\n\nOne last note on the topic of Bermanisms. I have a friend that is very good at creating Bermanisms and likes to create them for many of his work colleagues. So if you would like to be as unpopular as this guy is around the office, I suggest that you try using an LLM to Bermanize people at your workplace!\n\n[b]Update: March 6, 2026[/b]\n\nGPT 5.4 (the best new model for the moment) came out yesterday so I had to try it out. Overall, OpenAI is still worse than Gemini and Anthropic at making Bermanisms, but 5.4 is definitely better than GPT 5.2. It produced lots of really bad ones and it tends to rely too much on single-word nicknames. But here are some of the best ones that it produced:\n\nPatrick “Go Big or Go” Mahomes[br]George “Little by” Kittle[br]Pat “For” Surtain[br]T.J. “Guess” Watt[br]De’Von “No Pain, No” Achane[br]Christian “Elementary, My Dear” Watson[br]Brian “Disco Inferno, Burn Baby” Burns[br]Ja’Marr “The Thrill of the” Chase[br]Khalil “Salt” Shakir[br]Woody “On Your” Marks[br]Aidan “Starsky and” Hutchinson (YET AGAIN)",
          "caption": "",
          "imageSrc": "./assets/Berman.png",
          "imageAlt": "Chris Berman",
          "imageStyle": "small-center",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "writing",
      "title": "NBA analytics blog at Extra Pass Analytics",
      "slug": "nba_analytics_blog",
      "importance": 99,
      "metaDescription": "Posting about the NBA using advanced analytics.",
      "homeCardText": "Posting about the NBA using advanced analytics.",
      "archiveCardText": "Posting about the NBA using advanced analytics.",
      "archiveCardClass": "",
      "pageIntroText": "",
      "detailPageEnabled": false,
      "homeHref": "https://nbaextrapass.xyz/blog",
      "archiveHref": "https://nbaextrapass.xyz/blog",
      "blocks": [
        {
          "type": "text",
          "delay": "",
          "heading": "",
          "text": "",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "writing",
      "title": "Don't be this guy",
      "slug": "dont_be_this_guy",
      "importance": 85,
      "metaDescription": "An unsuccessful pickleball poach and video evidence of a bad kitchen line call",
      "homeCardText": "An unsuccessful pickleball poach and video evidence of a bad kitchen line call",
      "archiveCardText": "An unsuccessful pickleball poach and video evidence of a bad kitchen line call",
      "archiveCardClass": "",
      "pageIntroText": "",
      "detailPageEnabled": true,
      "homeHref": "./dont_be_this_guy.html",
      "archiveHref": "./dont_be_this_guy.html",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "",
          "text": "Nice dig to thwart my poach, but then the guy calls me for kitchen line violation in an open play game. Come on, man! That would call would be sus in rec play if I touched the line, which I did not.",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "embed",
          "delay": "delay-3",
          "heading": "",
          "text": "",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "Open on YouTube",
          "headerLinkHref": "https://youtu.be/kw7LRNahQg8",
          "embedSrc": "https://www.youtube.com/embed/kw7LRNahQg8",
          "embedTitle": "Don't be this guy video",
          "embedHeight": "560px",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "writing",
      "title": "Sol LeWitt",
      "slug": "sol_lewitt",
      "importance": 50,
      "metaDescription": "I'm really into the conceptual artist, Sol LeWitt.",
      "homeCardText": "I'm really into the conceptual artist, Sol Lewitt.",
      "archiveCardText": "I'm really into the conceptual artist, Sol Lewitt.",
      "archiveCardClass": "",
      "pageIntroText": "I'm really into the conceptual artist, Sol LeWitt.",
      "detailPageEnabled": true,
      "homeHref": "./sol_lewitt.html",
      "archiveHref": "./sol_lewitt.html",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "",
          "text": "I was never interested in art until around 2010, when I first discovered Sol LeWitt. I was visiting my Dad in Beacon, NY and had some time to kill. I decided to go to [link https://www.diaart.org/visit/visit-our-locations-sites/dia-beacon-beacon-united-states]Dia Beacon[/link], a modern art museum built in 2003 that transformed Beacon into a significant arts community. At the time they had a large [link https://diaart.org/program/past-programs/sol-lewitt-drawing-series-exhibition/page/31/year/2007]exhibition[/link] of LeWitt’s Wall Drawings. I was blown away by scale of these massive works of art. For example, [link https://massmoca.org/event/walldrawing1211/]Wall Drawing #1211[/link] is 192 drawings laid out in a 4 x 48 grid, each one a square meter in size, so this one work of art is around 5 meters tall and 50 meters wide (allowing for white space on the borders)! Something about the algorithmic, non-arbitrary design of all the pieces spoke to me. Afterward, I started researching LeWitt and learned that he had just passed away in 2007. And I learned about [link https://www.tate.org.uk/art/art-terms/c/conceptual-art]conceptual art[/link], a movement LeWitt helped popularize in the 1960s.\n\nOne key aspect of conceptual art is that the idea behind the artwork is primary and that the execution of the artwork is perfunctory. As an example, the [link ./assets/lewitt, sol, drawing series.pdf]Wall Drawings[/link] at Dia Beacon that I referred to earlier, were executed by two teams of assistants under LeWitts direction, but LeWitt did not do any of the physical work himself. More interestingly, if you purchase a Sol LeWitt Wall Drawing ([link https://www.sothebys.com/en/auctions/ecatalogue/2018/contemporary-art-day-sale-n09933/lot.109.html]it will cost you anywhere from $150K to $1M+[/link]), what you actually get is a [i]Ceritificate of Authenticity and Diagram[/i]. This gives you the exclusive right to have the work installed by a master craftsman (sold separately) on any one wall that you own or have permission to install on. If you have it installed on your living room wall and then sell the piece to someone else, you need to uninstall it before the new owner installs it on the wall of their choosing.\n\nMASS MoCA in North Adams, MA has one of the more incredible art exhibitions on the planet. They have 105 massive LeWitt Wall Drawings in a 27,000 sq ft building. [link https://massmoca.org/sol-lewitt/]Sol LeWitt: A Wall Drawing Retrospective[/link] was opened in 2008 and is scheduled to stay at MASS MoCA until the year 2043(!).",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "image",
          "delay": "delay-3",
          "heading": "",
          "text": "",
          "caption": "Composite Series (1970.01), Set of 5 silkscreens, Edition of 150, Sarah Lawrence Press.",
          "imageSrc": "./assets/sol_lewitt_Composite_Series_1971.png",
          "imageAlt": "Sol LeWitt Composite Series 1971",
          "imageStyle": "full",
          "imageLink": "https://www.sollewittprints.org/artwork/lewitt-raisonne-1970-01/",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "image",
          "delay": "",
          "heading": "",
          "text": "",
          "caption": "All One, Two, Three, and Four Part Combinations of Lines in Four Directions and Four Colors, Each Within a Square (1983.10), Silkscreen, Edition of 100, The Paris Review.",
          "imageSrc": "./assets/sol_lewitt_Paris_Review_1983.png",
          "imageAlt": "Sol LeWitt Paris Review 1983",
          "imageStyle": "full",
          "imageLink": "https://www.sollewittprints.org/artwork/lewitt-raisonne-1983-10/",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "links",
          "delay": "",
          "heading": "Sol LeWitt Links",
          "text": "",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": [
            {
              "label": "Sol LeWitt: A Wall Drawing Retrospective",
              "href": "https://massmoca.org/sol-lewitt/"
            },
            {
              "label": "Sol LeWitt Prints Catalogue Raisonne",
              "href": "https://www.sollewittprints.org/"
            },
            {
              "label": "Dia Beacon",
              "href": "https://diaart.org/visit/visit-our-locations-sites/dia-beacon-beacon-united-states"
            },
            {
              "label": "Midjourney takes on Sol LeWitt's Wall Drawings",
              "href": "https://www.amygoodchild.com/blog/midjourney-sol-lewitt"
            },
            {
              "label": "Conversation, Sol LeWitt Wall Drawings: Maintaining a Legacy",
              "href": "https://youtu.be/UNbOVR4kw4U"
            }
          ]
        },
        {
          "type": "embed",
          "delay": "",
          "heading": "All Non-Empty Combinations of Four Animations",
          "text": "A p5.js sketch I made inspired by Lewitt's Paris Review and Composite Series works.\n\nClick anywhere on the sketch and press the 'h' key to customize the parameters of the sketch.\nPress 'h' again to go back to the canvas.",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "Open in p5 Editor",
          "headerLinkHref": "https://editor.p5js.org/millxing/sketches/4F7tdPL3Y",
          "embedSrc": "https://editor.p5js.org/millxing/full/4F7tdPL3Y",
          "embedTitle": "All Non-Empty Combinations of Four Animations p5.js sketch",
          "embedHeight": "72vh",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "writing",
      "title": "Legal Realignment at the Supreme Court",
      "slug": "warren",
      "importance": 25,
      "metaDescription": "Harvard Law Professor Richard M. Re argues that legal ideologies are not permanently tied to either judicial constraint or judicial discretion.",
      "homeCardText": "Richard M. Re argues that legal ideologies are not permanently tied to either judicial constraint or judicial discretion.",
      "archiveCardText": "Richard M. Re argues that legal ideologies are not permanently tied to either judicial constraint or judicial discretion.",
      "archiveCardClass": "",
      "pageIntroText": "March, 2026\n\nHarvard Law Professor Richard M. Re has a really interesting thesis about the Supreme Court. His claim is that legal ideologies are not permanently connected to the principles of \"constraint\" (formalism, textualism, strict rules) or \"discretion\" (flexibility, purposivism, judicial empowerment). The side in power favors judicial discretion because it gives them the flexibility to implement the partisan agenda they favor. The side out of power favors judicial constraint because it limits the power of the majority. His papers [link https://lawreview.uchicago.edu/print-archive/legal-realignment]Legal Realignment[/link] (2024) and [link https://harvardlawreview.org/print/vol-139/to-a-conservative-warren-court/]Foreword: To A Conservative Warren Court[/link] (2025) explore this idea in depth and analyze it in the context of today's Supreme Court.\n\nAs an untrained, casual observer of the Supreme Court, I was always confused by the legal philosophies supposedly underlying Supreme Court decisions. It just seemed that principled adherence to those philosophies should result in more opinions that go against the partisan leanings of the justices.",
      "detailPageEnabled": true,
      "homeHref": "./warren.html",
      "archiveHref": "./warren.html",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "",
          "text": "Update 2026-03-02: The Supreme Court vacated a U.S. Appeals Court stay (9th Circuit) in Mirabelli v. Bonta. This ruling reinstates a federal district court ruling that prohibits California schools from concealing a child's gender presentation from their parents and requires the schools to follow parental instruction regarding the names and pronouns that their children use.\n\nThis ruling is consistent with Re's thesis of legal realignment in that conservatives are basing the ruling in part on \"substantve due process\", specifically in Barrett's concurrence (joined by Roberts and Kavanaugh). The conservatives usually argue that judges shouldn't find \"unexpressed rights\" in the Constitution (the basis for overturning Roe. v. Wade). In this case, they were OK with protecting the unexpressed rights of parents.",
          "caption": "",
          "imageSrc": "./assets/RE_X_2026-03-03.png",
          "imageAlt": "Update 2026-03-02: Mirabelli v. Bonta",
          "imageStyle": "full-white",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "pdf",
          "delay": "delay-3",
          "heading": "",
          "text": "",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "Open Legal Realignment (2024) PDF",
          "headerLinkHref": "./assets/legal_realignment.pdf",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "./assets/legal_realignment.pdf",
          "pdfTitle": "Legal Realignment PDF",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "embed",
          "delay": "delay-4",
          "heading": "",
          "text": "This Advisory Opinions podcast features an interview with Richard Re about his Conservative Warren Court essay. Re's latest paper analogizes today's Supreme Court with the Warren Court, in that they both had a durable ideologically aligned majority acting as a \"corrective force\" to reshape American society and overturn long-standing precedents.",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "https://open.spotify.com/embed/episode/7Jlz55uj6BZ7khnFMf4UYX?utm_source=generator",
          "embedTitle": "Advisory Opinions episode on Legal Realignment",
          "embedHeight": "352px",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "pdf",
          "delay": "delay-5",
          "heading": "",
          "text": "",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "Open Foreword: To A Conservative Warren Court (2025) PDF",
          "headerLinkHref": "./assets/conserv_warren_court.pdf",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "./assets/conserv_warren_court.pdf",
          "pdfTitle": "Foreword: To A Conservative Warren Court PDF",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    }
  ],
  "projects": [
    {
      "kind": "projects",
      "title": "Star Citadel",
      "slug": "star_citadel",
      "importance": 15,
      "metaDescription": "",
      "homeCardText": "I made an emulation of my favorite childhood arcade game, Star Castle. ",
      "archiveCardText": "I made an emulation of my favorite childhood arcade game, Star Castle. ",
      "archiveCardClass": "",
      "pageIntroText": "",
      "detailPageEnabled": true,
      "homeHref": "./star_citadel.html",
      "archiveHref": "./star_citadel.html",
      "blocks": [
        {
          "type": "text",
          "delay": "",
          "heading": "",
          "text": "I made an emulation of my favorite childhood arcade game, [link https://en.wikipedia.org/wiki/Star_Castle]Star Castle[/link].\n\nStar Castle is a 1980 multidirectional shooter video game developed and published by Cinematronics for arcades. The game involves obliterating a series of defenses orbiting a stationary turret in the center of the screen. The arcade game uses vector graphics on a black and white display, with the colors of the rings and screen provided by a transparent plastic overlay. Star Castle was designed by Tim Skelly and programmed by Scott Boden; Skelly created a number of other vector games for Cinematronics, including Starhawk, Armor Attack, and Rip Off. A Vectrex port of Star Castle was released in 1983.\n\nThe object of Star Castle is to destroy an enemy cannon which sits in the center of three concentric, rotating energy shield rings while avoiding or shooting \"mines\"–enemies that spawn from the core, pass through the energy rings, and then home in on the player's ship. The player's spaceship can rotate, thrust forward, and fire small projectiles. The cannon's shields are composed of twelve sections, and each section takes two hits to destroy. Once a section is breached, rings beneath it are exposed to fire.\n\nA color overlay tints the rings yellow, orange, and red and the rest of the playfield blue. Once the innermost ring has been breached, the central weapon is susceptible to attack, but the player is also more vulnerable at this point, as with the shield rings eliminated, the gun can fire out a large projectile that hisses with white noise. Moreover, the central core tracks player movement at all times. If the player manages to hit the cannon, it explodes violently, collapsing the remnants of the shield rings, and an extra ship is awarded. The next level then starts with a new gun and fully restored shield rings, but the difficulty is increased (the mines move more rapidly, the rings rotate more quickly, and the core tracks the player at a faster rate).\n\nIf the player completely destroys the outermost shield ring, the cannon will create a new one. The middle ring expands to replace the lost outer ring, the inner ring replaces the middle, and a new ring emerges from the core to become the inner ring. Therefore, in order to penetrate the cannon's defenses, the player must be careful not to completely obliterate the outer ring.\n\nThe three homing mines will destroy the player's ship on contact. The mines can be destroyed, but they are very small and difficult to hit, and the player does not receive points for destroying them. Mines are revived when shield rings regenerate (some variants keep three mines churning constantly so that a new mine respawns from the core as soon as one is destroyed). As the player progresses through the levels, the mines get faster and faster, forcing the player to keep moving to avoid them.",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        },
        {
          "type": "text",
          "delay": "",
          "heading": "",
          "text": "[link https://millxing.github.io/starcitadel/]Play my Star Castle inspired emulation, Star Citadel[/link]",
          "caption": "",
          "imageSrc": "./assets/starcit01.png",
          "imageAlt": "Screenshot of Star Citadel gameplay",
          "imageStyle": "full",
          "imageLink": "https://millxing.github.io/starcitadel/",
          "imagePosition": "after",
          "extraClasses": [
            "text-center"
          ],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "projects",
      "title": "Extra Pass Anaytics",
      "slug": "extrapass",
      "importance": 100,
      "metaDescription": "ExtraPass: Advanced NBA analytics with a Four Factor framework.",
      "homeCardText": "Advanced basketball statistics analysis for NBA games and teams.",
      "archiveCardText": "Advanced basketball statistics analysis for NBA games and teams.",
      "archiveCardClass": "",
      "pageIntroText": "Advanced basketball statistics analysis using a Four Factor framework.",
      "detailPageEnabled": true,
      "homeHref": "https://extrapass.onrender.com/",
      "archiveHref": "https://extrapass.onrender.com/",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "Overview",
          "text": "ExtraPass explores team and player performance through pace, shooting efficiency, turnovers, and rebounding. This page is a project landing page for the portfolio.\n\n- Four-factor team analysis for all games (2000-2026)\n- Play-by-play timelines with win probabilities\n- Advanced stats league summary over custom horizons\n- Statistical trend charts\n- Contributions to performance over custom horizons",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "projects",
      "title": "Brookline Town Meeting Votes",
      "slug": "tm",
      "importance": 90,
      "metaDescription": "App for viewing Town Meeting votes and how Town Meeting Members voted.",
      "homeCardText": "App for viewing Town Meeting votes and how Town Meeting Members voted",
      "archiveCardText": "App for viewing Town Meeting votes and how Town Meeting Members voted",
      "archiveCardClass": "",
      "pageIntroText": "App for viewing Town Meeting votes and how Town Meeting Members voted",
      "detailPageEnabled": true,
      "homeHref": "https://millxing.github.io/TM/TMMvotes.html",
      "archiveHref": "https://millxing.github.io/TM/TMMvotes.html",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "Overview",
          "text": "This project page summarizes a civic data tool for exploring motions, outcomes, and individual voting records across Brookline Town Meeting sessions.\n\n- Town Meeting Data from 2022 to 2025\n- View by Vote\n- View by Member\n- TMM networks\n- Vote History w/ AI summaries\n- Precinct Votes\n- Closest Votes\n- Principal Component Analysis\n- TMM emails",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "projects",
      "title": "iSocrateez",
      "slug": "isocrateez",
      "importance": 10,
      "metaDescription": "Give iSocrateez a moral or ethical dilemma and a Consequentialism-Deontological Index score and it will give you customized advice.",
      "homeCardText": "Are you more about the \"ends justifying the means\" or more about \"the principle is what matters\"? iSocrateez will give you customized advice. What could go wrong?",
      "archiveCardText": "Are you more about the \"ends justifying the means\" or more about \"the principle is what matters\"? iSocrateez will give you customized advice. What could go wrong?",
      "archiveCardClass": "",
      "pageIntroText": "Give iSocrateez a moral or ethical dilemma and a Consequentialism-Deontological Index score (i.e. are you more the \"ends justify the means\" or \"the principle is what matters\") and it will give you customized advice.",
      "detailPageEnabled": true,
      "homeHref": "https://chatgpt.com/g/g-684ac617a220819198baae3dd95e0cb4-isocrateez",
      "archiveHref": "https://chatgpt.com/g/g-684ac617a220819198baae3dd95e0cb4-isocrateez",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "Overview",
          "text": "iSocrateez is a custom GPT built to respond to moral and ethical dilemmas with advice that matches a user's Consequentialism-Deontological Index.\n\n- Moral and ethical dilemma prompts\n- Advice shaped by your stated philosophy\n- Designed as an interactive thought experiment",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "projects",
      "title": "Longwood Mall",
      "slug": "longwoodmall",
      "importance": 5,
      "metaDescription": "longwoodmall.org, currently being modernized and migrated to a new platform.",
      "homeCardText": "Website for Longwood Mall, currently being modernized and migrated to a new platform.",
      "archiveCardText": "Website for Longwood Mall, currently being modernized and migrated to a new platform.",
      "archiveCardClass": "",
      "pageIntroText": "Website for Longwood Mall, currently being modernized and migrated to a new platform. Visit [link https://longwoodmall.org/]longwoodmall.org[/link].",
      "detailPageEnabled": true,
      "homeHref": "https://longwoodmall.org/",
      "archiveHref": "./longwoodmall.html",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "Overview",
          "text": "This project page highlights the ongoing refresh of longwoodmall.org as the site is updated and moved to a new platform.\n\n- Public-facing site for Longwood Mall\n- Modernization currently in progress\n- Migration to a new platform underway",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    },
    {
      "kind": "projects",
      "title": "Washington Street Journal",
      "slug": "wsj",
      "importance": 1,
      "metaDescription": "Resource for understanding Brookline's finances.",
      "homeCardText": "Resource for understanding Brookline's finances.",
      "archiveCardText": "Resource for understanding Brookline's finances.",
      "archiveCardClass": "",
      "pageIntroText": "Resource for understanding Brookline's finances.",
      "detailPageEnabled": true,
      "homeHref": "https://millxing.github.io/BF/",
      "archiveHref": "https://millxing.github.io/BF/",
      "blocks": [
        {
          "type": "text",
          "delay": "delay-2",
          "heading": "Overview",
          "text": "This project page introduces a public-facing resource designed to make local financial documents and budget context easier to understand.\n\n- Committee reports\n- Budget data\n- News and opinions\n- Links\n- Meeting agendas and media",
          "caption": "",
          "imageSrc": "",
          "imageAlt": "",
          "imageStyle": "full",
          "imageLink": "",
          "imagePosition": "before",
          "extraClasses": [],
          "headerLinkLabel": "",
          "headerLinkHref": "",
          "embedSrc": "",
          "embedTitle": "",
          "embedHeight": "",
          "pdfSrc": "",
          "pdfTitle": "",
          "tableHeaders": [],
          "tableRows": [],
          "linkItems": []
        }
      ]
    }
  ]
};

export default siteContent;
